server:
  port: 8888
spring:
  profiles:
    active: ${SPRING_PROFILE:native}
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations