eureka:
  instance:
    hostname: discovery-service
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka
spring:
  profiles:
    active: ${SPRING_PROFILE:native}
  cloud:
    config:
      override-system-properties: false