server:
  port: 8222
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb:http://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
        - id: project-service
          uri: lb:http://PROJECT-SERVICE
          predicates:
            - Path=/api/v1/projects/**
        - id: bug-service
          uri: lb:http://BUG-SERVICE
          predicates:
            - Path=/api/v1/bugs/**
        - id: comment-service
          uri: lb:http://COMMENT-SERVICE
          predicates:
            - Path=/api/v1/comments/**